version: "2"

linters:
  default: standard
  exclusions:
    warn-unused: true
    rules:
      - linters: [gosec]
        text: "G401: Use of weak cryptographic primitive"
        # justification: "MD5 required by zalo"
      - linters: [gosec]
        text: "G501: Blocklisted import crypto/md5: weak cryptographic primitive"
        # justification: "MD5 required by zalo"
      - linters: [gosec]
        text: "G304: Potential file inclusion via variable"
        
  enable:
    - cyclop
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (net.Conn).Close
        - (*compress/gzip.Reader).Close
  
formatters:
  enable:
    - gofumpt
    - goimports

